name: 'spotify_dbt'
version: '1.0.0'
config-version: 2

profile: 'spotify_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify_dbt:
    input:
      +materialized: view
    output:
      +materialized: table